dist: trusty
language: bash
#os:
#- linux
#- osx

global:
  - BUILD_GOARCH=amd64
matrix:
  - BUILD_GOOS=linux
  - BUILD_GOOS=darwin
  - BUILD_GOOS=windows

go:
  - 1.7
install: true

script:
- go get "github.com/sparrc/go-ping"
- cd /home/travis/build/werfty/multitool
- go build werfty-mt.go
- ls -al werfty-mt
- ./werfty-mt
