dist: trusty
language: bash
os:
- linux
- osx
go:
  - 1.7
install: true

script:
- go get "github.com/sparrc/go-ping"
- cd /home/travis/build/werfty/multitool
- go build werfty-mt.go
- ls -al werfty-mt
